### PR TITLE
Convert Untangled Server to Supply Reusable Middleware for general server building needs

### PR DESCRIPTION
**Pull request by awkay**

### CODE REVIEW

**Comment by Pancia** [comment]
untangled component handler function should take `:libraries` so we can compose in things, like the image library from untangled-components

**Comment by awkay** [comment]
We need a component that supplies a function (api-handler) that can act as a Ring middleware handler. The user will be required to install transit earlier in the ring chain (so they can extend it).

**Comment by Pancia** [comment]
Confirming that this is backwards compatible here: https://github.com/untangled-web/untangled-cookbook/commit/505839a5a51083c4e8d5d06b772d852c216b26ce
@awkay

**Comment by awkay** [comment]
@Pancia merged and pushed to clojars as 0.6.3-SNAPSHOT

**Pull request merged**
